// --- DATA PRODUK (RINGKAS TANPA DESKRIPSI MANUAL) ---
const products = [
    // --- PRODUK SHOPEE ---
	// --- SHINZUI ---
    {
        id: 1,
        name: "Shinzui Body Cleanser Sakura Refill 180gr",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 19.500",
        originalPrice: "Rp 30.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7r98w-lmiertxcrr1d07",
        link: "https://s.shopee.co.id/4VbQfi4crI"
    },
    {
        id: 2,
        name: "Shinzui Body Cleanser Sakura Pump 480gr",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 53.000",
        originalPrice: "Rp 60.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztn-mqd4pwfqyv4f4d@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/AUsdpX6Kei"
    },
    {
        id: 3,
        name: "Shinzui WHITEssentials Acne Calm Brightening Facial Wash CICA 80ml | Sabun Cuci Muka Mencerahkan untuk Kulit Berminyak",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 28.600",
        originalPrice: "Rp 50.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztj-mr1do4ibljb6a2@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/qi9MGXA5j"
    },
    {
        id: 4,
        name: "Shinzui Whitessentials Brightening Serum Moisturizer 15gr Travel skincare",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 33.000",
        originalPrice: "Rp 60.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztn-mr1arsypl3wmea@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1LePxc3N6H"
    },
    {
        id: 5,
        name: "Shinzui Skin Lightening Body Lotion Sakura 210ml",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 27.900",
        originalPrice: "Rp 35.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7r98u-lmif5qfwd7hg0b@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/3ViuXfEt4i"
    },
    {
        id: 6,
        name: "Shinzui Glow Spa Exfoliating Gel Ichigo 260ml (Ukuran besar, Limited Stock)",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 19.845",
        originalPrice: "Rp 50.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7r991-llip3msqgaaa8e@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7AcCuQRP7Z"
    },
    {
        id: 7,
        name: "Shinzui Glow Spa Exfoliating Gel Cica 260ml (Ukuran Besar, Limited Stock)",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 19.845",
        originalPrice: "Rp 50.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7r98x-llip3msqj357f8@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/8pkQtVtIrB"
    },
	{
        id: 8,
        name: "Shinzui Whitessentials Brightening Emulsion 50 ml Skincare",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 58.500",
        originalPrice: "Rp 90.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zto-mr1a8l8hrwueb1@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/LlsluyndD"
    },
	{
        id: 9,
        name: "Shinzui Skin Lightening Body Lotion Matsu 100ml",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 16.000",
        originalPrice: "Rp 28.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7r98w-lmif5qfwya32fe@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7Kvd6np0DS"
    },
	{
        id: 10,
        name: "Shinzui Whitessentials Gel Mini Barrier Set (Moisturizer Gel 10 gr, Facial Wash Cica 20 ml) - Skincare",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 25.500",
        originalPrice: "Rp 50.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zto-mr1b81j9ph4xfc.webp",
        link: "https://s.shopee.co.id/9fJXt786im"
    },
	{
        id: 11,
        name: "Shinzui Whitessentials Moisturizer Light 30 gr - Skincare Pelembab Mencerahkan",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 51.000",
        originalPrice: "Rp 90.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztm-mr1a8l8htbeueb@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/60QFWOkPWD"
    },
	{
        id: 12,
        name: "Shinzui Glow Spa Exfoliating Gel Honey 260ml isi 2pcs (Ukuran Besar, Limited Stock)",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 25.000",
        originalPrice: "Rp 100.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wu-mn22oej1wt1kd8@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9zwOHvJadf"
    },
	{
        id: 13,
        name: "[Hemat isi 4] Shinzui Body Scrub Mix 2 pcs Kirei, 2 pcs Sakura 200gr - Scrub Badan Mencerahkan",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 70.000",
        originalPrice: "Rp 112.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wt-mn2aanfpowlcc8@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/W5IyU4csS"
    },
	{
        id: 14,
        name: "Shinzui Whitessentials Bundling Sunscreen 30ml FREE Moisturizer Gel 10gr - Skincare",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 35.000",
        originalPrice: "Rp 55.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zto-mr1arsypqq6ea0@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/AAFoUGYRNY"
    },
	{
        id: 15,
        name: "Shinzui Body Cleanser Matsu Pump 480gr + Body Scrub Matsu 200gr",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 63.000",
        originalPrice: "Rp 77.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-81ztt-mmvg2zh8adq845@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/903r68kvwl"
    },
	{
        id: 16,
        name: "Shinzui Whitessentials Brightening Emulsion 50 ml Skincare",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 58.000",
        originalPrice: "Rp 90.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zto-mr1a8l8hrwueb1@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/80BJuJk8vq"
    },
	{
        id: 17,
        name: "Shinzui Body Cleanser Matsu Refill 725gr isi 3pcs",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 130.950",
        originalPrice: "Rp 210.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wg-mp3ek9bt5tzh88@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/2qTDkqQRDn"
    },
	{
        id: 18,
        name: "Shinzui Skin Lightening Body Lotion Hana 210ml",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 28.000",
        originalPrice: "Rp 35.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7r98o-lmifkefvs51oc2@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/AAFoUKsCjd"
    },
	{
        id: 19,
        name: "Shinzui Whitessentials Gel Mini Barrier Set (Moisturizer Gel 10 gr, Facial Wash Cica 20 ml) - Skincare",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 25.500",
        originalPrice: "Rp 50.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zto-mr1b81j9ph4xfc@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/8pkQtuFEPI"
    },
	{
        id: 20,
        name: "Shinzui Brightening Essence Toner 50 ml Skincare",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 72.080",
        originalPrice: "Rp 120.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztc-mr1b81j8dptsa2@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/AKZEgg8QhM"
    },
	{
        id: 21,
        name: "Shinzui Body Cleanser Kensho Refill 380gr isi 3pcs",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 103.500",
        originalPrice: "Rp 135.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wj-mnl9z2rl3ojk96@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/6L35vLgIPE"
    },
	{
        id: 22,
        name: "Shinzui Whitessentials Brightening Serum 20 ml Skincare FREE Shinzui Moisturizer 5gr",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 41.000",
        originalPrice: "Rp 80.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztl-mr1arsypnx1i6d.webp",
        link: "https://s.shopee.co.id/LlsmL27Aw"
    },
	{
        id: 23,
        name: "Shinzui Body Cleanser Sakura Botol 225gr",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 28.000",
        originalPrice: "Rp 40.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zto-mqd5xpj6h72mad@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/111ZZa3ZYp"
    },
	{
        id: 24,
        name: "Shinzui Whitessentials All in One Brightening Micellar Water Cleansing 125+25 ml EXTRA | Pembersih Muka dan Make Up 1x Swipe",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 36.000",
        originalPrice: "Rp 70.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztp-mr1do4i7b0uk2f.webp",
        link: "https://s.shopee.co.id/7Kvd7FvyiR"
    },
	{
        id: 25,
        name: "Shinzui Mini Basic Essential ( 1 pcs Shinzui Facial Wash 20 ml, Shinzui Moisturizer 15 gr , Shinzui Sunscreen 30 ml ) / Travel Size isi 3",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 68.400",
        originalPrice: "Rp 115.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztn-mr1a8l8hqi9yef@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1VxqAYQ1xY"
    },
	{
        id: 26,
        name: "Shinzui Bar Soap Sakura 80gr 3pcs",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 19.000",
        originalPrice: "Rp 21.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7r98z-lmie5bh4ot6384@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/3B649eW96G"
    },
	{
        id: 27,
        name: "Shinzui Whitessentials Brightening Serum Sunscreen SPF 35 PA +++ 30 ml FREE Facial Wash 20 ml - Skincare",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 35.000",
        originalPrice: "Rp 55.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztj-mr1a8l8hw4jq73.webp",
        link: "https://s.shopee.co.id/5q6pKZVlSC"
    },
	{
        id: 28,
        name: "Shinzui Whitessentials Barrier ( 1 pcs Shinzui Facial Wash 80 ml, 1 pcs Shinzui Moisturizer 30 gr ) isi 2 skincare",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 87.000",
        originalPrice: "Rp 125.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztp-mr1a8l8hupza01@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/4LI1XrUUMV"
    },
	{
        id: 29,
        name: "Shinzui Whitessentials Maintain Cleanse & Protect Set 4 in 1 (Micellar Water 125+25ml EXTRA, Sunscreen 30ml FREE Facial Wash",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 104.000",
        originalPrice: "Rp 175.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zte-mr1b81j8cb9c86@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/60QFWwStaZ"
    },
	{
        id: 30,
        name: "Shinzui WHITEssentials Double Brightening Facial Wash Snow Mushroom 80ml",
        category: "Kecantikan",
        subCategory: "Shinzui",
        platform: "Shopee",
        price: "Rp 28.800",
        originalPrice: "Rp 50.000",
        badge: "SHINZUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztd-mr1do4i79ma443.webp",
        link: "https://s.shopee.co.id/8KoBgQSgH7"
    },
	
	// --- WARDAH ---
	{
        id: 31,
        name: "WARDAH Facial Wash All Series - Acnederm, C-Defense, Lightening Lightplus, Perfect Bright Now, Nature Daily, Crystal Secret, Renew You",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp 21.375 - Rp 91.200",
        originalPrice: "Rp 43.475 - Rp 163.200",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztp-mqvrpxgpdouaf2@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/2LWyfW1RS1"
    },
	{
        id: 32,
        name: "Wardah Sunscreen UV Shield All Series (Airy Smooth Essential Gel Acne Calming Aqua Fresh Tone Up Physical) Sunscreen SPF 50 PA SPF 35ws E1`q",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp 38.315",
        originalPrice: "Rp 71.100",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztk-mqvrpxg9f6koab.webp",
        link: "https://s.shopee.co.id/7KveciipPS"
    },
	{
        id: 33,
        name: "Wardah Sunscreen UV Shield Acne Calming Sunscreen Moisturizer SPF 35 PA+++ Single, Twinpack, Triple Pack Sunscreen Wajah",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp 39.105 - Rp 107.835",
        originalPrice: "Rp 71.100 - 213.300",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztg-mqvs01xjrx8ic1@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/4futRpsACM"
    },
	{
        id: 34,
        name: "NEW FORMULA AND PACKAGING! Wardah UV Shield Bright-C Hydrating Sunscreen Serum SPF 35 PA+++ Sunscreen 0% Alkohol",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp 39.105 - 180.000",
        originalPrice: "Rp 71.100 - 355.500",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-823ph-mpd2jmy1ahhnbb.webp",
        link: "https://s.shopee.co.id/7prvDfbiX8"
    },
	{
        id: 35,
        name: "WARDAH Brightening Crystal Secret NMF Amino AHA PHA Clarifying Foaming Cleanser 100 ml - Skincare",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp 42.500 - Rp 245.488",
        originalPrice: "Rp 74.700 - Rp 488.700",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zti-mqvs01xjw4xu77@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/qiAspAPvl"
    },
	{
        id: 36,
        name: "Wardah Micellar Water All Series - Perfect Bright, Calm and Soothe Nature Daily, Acnederm, Lightening Oil Infused - Pembersih Wajah",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp 47.700 - Rp 197.200",
        originalPrice: "Rp 47.700 - 246.070",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztf-mqvs01xfu1vr93@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9Kgj0SUEiJ"
    },
	{
        id: 37,
        name: "WARDAH Serum All Series Untuk Semua Jenis Kulit - Serum Mencerahkan Wajah, Melembabkan Wajah, Spray Serum, Niacinamide",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp 68.400 - Rp 255.550",
        originalPrice: "Rp 135.000 - 459.000",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wl-mmttkfopclc453.webp",
        link: "https://s.shopee.co.id/LluHw25vk"
    },
	{
        id: 38,
        name: "WARDAH Gel Moisturizer Series 30 g - Calming, Brightening, Soothing, Clarifying, Refining, Correcting, Revitalizing, Anti Aging",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp 56.050 - Rp 368.600",
        originalPrice: "Rp 102.600 - Rp 677.900",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zth-mqvrpxgp59fm48@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/2qTFGXpM4T"
    },
	{
        id: 39,
        name: "WARDAH Nature Daily Calm & Soothe Micellar Water - Skincare",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp 33.000 - Rp 116.000",
        originalPrice: "Rp 59.400 - Rp 197.200",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wp-mohr5ug75xjh39@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/2qTFGYgZ1p"
    },
	{
        id: 40,
        name: "WARDAH Serum Spray - Instant Glowing First Spray Serum - Spray On Serum 105 ml - Kulit lebih glowing dan kenyal, Pendukung Make Up",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp 110.000 - Rp 273.600",
        originalPrice: "Rp 259.000 - Rp 524.530",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztn-mqvrpxgpavpefe@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/3g2MG6Tm9T"
    },
	{
        id: 41,
        name: "WARDAH Crystal Secret All Series Lengkap - Menyamarkan Flek dan Bekas Jerawat, Perawatan Kulit Wajah Sebening Kristal, Skin Barrier",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp 33.725 - Rp 110.200",
        originalPrice: "Rp 63.900 - Rp 208.800",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztl-mqvrpxgp3uv698.webp",
        link: "https://s.shopee.co.id/3qLmSQW6cK"
    },
	{
        id: 42,
        name: "Wardah Sunscreen UV Shield Tinted Tone Up SPF 50 PA 30 ml - Makeup Primer, Base Make Up, Mencerahkan Wajah, Samarkan Noda",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp 63.360 - Rp207.100 ",
        originalPrice: "Rp106.880 - Rp393.300",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztj-mqvrpxgp9h4ye6.webp",
        link: "https://s.shopee.co.id/1Vxrg9VIuJ"
    },
	{
        id: 43,
        name: "WARDAH Paket 3 pcs Gel Moisturizer, Facial Wash, dan Serum - Bright Radiant, Bright Glowing, Calm Acne, Hydrated Plump, Nature Daily",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp120.980 - Rp332.025",
        originalPrice: "Rp236.300 - Rp627.300",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-82251-mip803u9l0qo5f@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9fJZPAwvHG"
    },
	{
        id: 44,
        name: "WARDAH Paket 5 pcs Skincare Solusi Masalah Kulit - Hydra Booster, Ultimate Bright, Brightening, Anti Aging, Lift Skin, Youthful",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp197.160 - Rp614.265",
        originalPrice: "Rp384.000 - Rp1.145.600",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wr-mmgugqx13pc5be.webp",
        link: "https://s.shopee.co.id/60QH2S0AL7"
    },
	{
        id: 45,
        name: "WARDAH Derma Sensitive Skin Rescue Moisturizer Neutrazen + Madecassoside 50g - Meredakan dan Menenangkan Jerawat",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp115.370 - Rp337.810",
        originalPrice: "Rp208.500 - Rp793.700",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztj-mr0u3ky8pjpge1@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/W5KUMDpEQ"
    },
	{
        id: 46,
        name: "WARDAH Collagen Moisturizer - Plump & Firm Recombinant Collagen + 2% Argireline Peptide Gel Moist - Glow Moisturizer",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "128.000 - Rp368.600",
        originalPrice: "Rp254.600 - Rp677.900",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zti-mqvrpxgp11qa47@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/3LPVrZsBa3"
    },
	{
        id: 47,
        name: "Wardah Acnederm Facial Wash Salicylic Acid Zinc Acne Clearing Low pH Foaming Cleanser - Sabun Cuci Muka Facewash Skincare",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp26.500 - Rp160.263",
        originalPrice: "Rp46.800 - Rp316.200",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-823qh-mpd2am3zplhe71@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1LeRTuun1W"
    },
	{
        id: 48,
        name: "NEW! Wardah UV Shield Sunscreen Spray Serum Ultra-Fine Mist Serum SPF 50+ PA++++ 50ml - Sunscreen Re-apply,Tekstur Ringan",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp88.110 - Rp209.760",
        originalPrice: "Rp151.300 - Rp410.300",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-822wg-mo53yal96qdc36@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/2BDYTSehZD"
    },
	{
        id: 49,
        name: "[BUY 2 GET 3 Free Micellar Water] TWINPACK Wardah UV Shield Airy Smooth Acne Calming Aqua Tone Up Physical Sunscreen - Skincare",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp75.050 - Rp507.450",
        originalPrice: "Rp142.200 - Rp897.000",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zti-mq5yeh55064va3@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/4Aycr9SQCa"
    },
	{
        id: 50,
        name: "Wardah Cleansing Oil LHA Camellia Oil Pore Purifying 140 ml-Cleansing oil membersihkan waterproof makeup dengan formula ringan",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp135.000 - Rp273.420",
        originalPrice: "Rp253.000 - Rp518.530",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224t-mile5bqotzb8d1@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/BSU5oT9W9"
    },
	{
        id: 51,
        name: "Wardah Sunscreen UV Shield Triple Pack Buy 3 Get 5 SPF 35 PA +++ / SPF 50 PA++++ (Airy Smooth, Essential Gel, Acne Calming",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp107.835 - Rp597.000",
        originalPrice: "Rp213.300 - Rp897.000",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztm-mqyfngetxtdze7@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/4LI33U8lHd"
    },
	{
        id: 52,
        name: "WARDAH Crystal Secret Essential Package (Cleanser 100 ml, Serum 20 ml, Day Cream 30 g) - Rangkaian Skincare Untuk Mencerahkan",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp97.940 - Rp222.855",
        originalPrice: "Rp197.200 - Rp468.900",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wq-mlvko8e5r9xk96@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9ANIoNhMeX"
    },
	{
        id: 53,
        name: "WARDAH Paket 4 pcs Skincare Solusi Masalah Kulit - Brightening Glow, Repair Barrier, Anti Wrinkle, Firm & Lift, Strong Barrier, Acne Solver",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp201.875 - Rp469.775",
        originalPrice: "Rp382.900 - Rp863.400",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztd-mqvs01xjp43m00@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/30mfT48Hou"
    },
	{
        id: 54,
        name: "WARDAH Serum Clinical Series - PDRN, Retinal, & Microneedle Serum Mencerahkan Wajah, Brightening, Hydrating, Anti Aging, Glowing",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp211.000 - Rp446.202",
        originalPrice: "Rp423.300 - Rp873.000",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztm-mr0u3ky8v5z8e0@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7AcEQjoRff"
    },
	{
        id: 55,
        name: "WARDAH CRYSTAL SECRET SERUM NIACINAMIDE Tranexamic Acid TXA + Alpha Arbutin Dark Spot Brightening Serum",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp92.650",
        originalPrice: "Rp187.200",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-7rdws-m0u0is0hjr8wf2@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/60QH2bnwgb"
    },
	{
        id: 56,
        name: "Wardah Microneedle Serum Skin Retexturing Serum Shot 30ml - Microspicule, Memperbaiki Tekstur Kulit, Bopeng, Glowing, Halus",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp211.000 - Rp478.800",
        originalPrice: "Rp423.300 - Rp926.800",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztq-mr0u3ky8zdok64@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1BL1HjxPvt"
    },
	{
        id: 57,
        name: "NEW! Wardah Toner Pad Madecassoside Ectoin Barrier Calming 50 pads / 100 ml - Untuk Semua Jenis Kulit, Meredakan Kulit Kemerahan",
        category: "Kecantikan",
        subCategory: "Wardah",
        platform: "Shopee",
        price: "Rp139.000 - Rp364.161",
        originalPrice: "Rp199.000 - Rp751.600",
        badge: "WARDAH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wo-mp8q96ad9l3h25@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/111b5Rtrns"
    },
	
	// --- SKINTIFIC ---
	{
        id: 58,
        name: "SKINTIFIC - Essence Toner Series | Niacinamide Brightening 5X Ceramide Calm Down Soothing Barrier Noda Hitam PIE&PIH 377 Pro",
        category: "Kecantikan",
        subCategory: "Skintific",
        platform: "Shopee",
        price: "Rp71.100",
        originalPrice: "",
        badge: "SKINTIFIC",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztj-mr2s99bip2ps53@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1943r47RC"
    },
	{
        id: 59,
        name: "SKINTIFlC - 3IN1 Instant Glowing Serum Spray 100ml | Radiance Booster Essence wajah Toner Centella Kulit Lebih Halus Lembab",
        category: "Kecantikan",
        subCategory: "Skintific",
        platform: "Shopee",
        price: "Rp65.700",
        originalPrice: "",
        badge: "SKINTIFIC",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztk-mr2pffks2p6v38@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1VxrqdTDOw"
    },
	{
        id: 60,
        name: "SKINTIFIC – 12% Acid Peeling Solution Glowing Serum Essence Eksfoliasi Wajah & Tubuh Cocok untuk Kulit Berjerawat, Komedo",
        category: "Kecantikan",
        subCategory: "Skintific",
        platform: "Shopee",
        price: "Rp94.410",
        originalPrice: "",
        badge: "SKINTIFIC",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztd-mr2phmc8m1aa8d@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/80BLaaz31U"
    },
	{
        id: 61,
        name: "SKINTIFIC - 5% Panthenol Acne Calming Water Gel 45g | Exfoliating Perawatan Wajah Calming untuk Melembabkan Whitening Brightening",
        category: "Kecantikan",
        subCategory: "Skintific",
        platform: "Shopee",
        price: "Rp112.500",
        originalPrice: "",
        badge: "SKINTIFIC",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztp-mr2psgfbahvo28@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/5LAaPi50y1"
    },
	{
        id: 62,
        name: "SKINTIFIC - TXA Niacinamide Brightening Cream- Wajah Krim Untuk Kulit Kusam/Berjerawat/All Skin Types - Brightening with TXA",
        category: "Kecantikan",
        subCategory: "Skintific",
        platform: "Shopee",
        price: "Rp112.500",
        originalPrice: "",
        badge: "SKINTIFIC",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224s-mjr03iy7e0ateb@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/2VqP2WFOgH"
    },
	{
        id: 63,
        name: "SKINTIFIC - Cleanser Series All-in-1 | Rose Glowing / Niacinamide Brightening/ 3X Acid Acne Calming/ Ectoin Essence /Panthenol Gentle",
        category: "Kecantikan",
        subCategory: "Skintific",
        platform: "Shopee",
        price: "Rp41.990",
        originalPrice: "",
        badge: "SKINTIFIC",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztk-mr2s99bino5cf2@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1qaiFK8BqS"
    },
	{
        id: 64,
        name: "SKINTIFIC - 3X Acid Acne Gel Cleanser 120ml | Salicilyc Acid Facial Wash Cleanser Wajah Untuk Kulit Jerawat Berminyak Gentle Exfoliating",
        category: "Kecantikan",
        subCategory: "Skintific",
        platform: "Shopee",
        price: "Rp83.700",
        originalPrice: "",
        badge: "SKINTIFIC",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zth-mr2s3fw1eayvad@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/gOkrC39YO"
    },
	{
        id: 65,
        name: "SKINTIFIC - Ectoin Essence Cleanser 80ml | Face Wash Reduce Redness Calming Down Anti-inflammatory Repair Barrier Brightening",
        category: "Kecantikan",
        subCategory: "Skintific",
        platform: "Shopee",
        price: "Rp58.990",
        originalPrice: "",
        badge: "SKINTIFIC",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7rbka-madmnt9oapcp74@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/3LPW29zykK"
    },
	{
        id: 66,
        name: "SKINTIFIC - Niacinamide Brightening Booster Essence Toner 80ml | Glowing Tranexamic Acid Eksfoliasi Wajah Exfoliating Acnes Badan",
        category: "Kecantikan",
        subCategory: "Skintific",
        platform: "Shopee",
        price: "Rp98.100",
        originalPrice: "",
        badge: "SKINTIFIC",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztg-mr2s3fvv45j41f@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9V09NTludi"
    },
	{
        id: 67,
        name: "[SIZE UP!!] SKINTIFIC - Glowing Brightening Cleanser 120ml | Niacinamide Facial Wash Kulit Kusam Sabun Cuci Muka Dullness Pore",
        category: "Kecantikan",
        subCategory: "Skintific",
        platform: "Shopee",
        price: "Rp52.990",
        originalPrice: "",
        badge: "SKINTIFIC",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zto-mr2pjh3fcg7g3b@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/AKZGN2MLVb"
    },
	{
        id: 68,
        name: "Glad2Glow Facial Wash All Series-Pembersih low pH lembut/niacinamide/brightening/ACNE/eksfoliasi/asam amino",
        category: "Kecantikan",
        subCategory: "G2G",        
		platform: "Shopee",
        price: "Rp29.000 - Rp93.800",
        originalPrice: "Rp49.375 - Rp129.000",
        badge: "G2G",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zti-mr1c5wdh6n7p6b@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/80BN894BTa"
    },
	{
        id: 69,
        name: "GLAD2GLOW 2%Niacinamide Brightening Tone Up Cream Day Cream Cerah Instan Moisturizer wajah cream pemutih wajah",
        category: "Kecantikan",
        subCategory: "G2G",        
		platform: "Shopee",
        price: "Rp33.900",
        originalPrice: "",
        badge: "G2G",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztq-mr1golniornr47@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/8KoDWmOqyj"
    },
	{
        id: 70,
        name: "[DISKON 60%] Glad2Glow Clay Stick&Face Mask Series-Pomegranate Brightening/Mugwort Acne/ Volcanic Pore-sleeping",
        category: "Kecantikan",
        subCategory: "G2G",        
		platform: "Shopee",
        price: "Rp30.900 - Rp140.179",
        originalPrice: "Rp97.800 - Rp219.000",
        badge: "G2G",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztj-mr132t8732tge3@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/5LAbxHZWi4"
    },
	{
        id: 71,
        name: "Glad2Glow Deep Pore Clean Facial Wash Pembersih Wajah Charcoa Volcanic Soil BHA Salicylic Acid Deep Cleansing Minyak Berlebih",
        category: "Kecantikan",
        subCategory: "G2G",        
		platform: "Shopee",
        price: "Rp37.900 - Rp219.500",
        originalPrice: "Rp49.375 - Rp259.000",
        badge: "G2G",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztq-mr1cgux4hiiv30@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/AUsi6os1on"
    },
	{
        id: 72,
        name: "Glad2Glow Serum Series-Peeling| Exfoliating | Mencerahkan Wajah | Retinol |Niacinamide| Dark Spot | Acne | Jerawat Glowing Brightening",
        category: "Kecantikan",
        subCategory: "G2G",        
		platform: "Shopee",
        price: "Rp39.000 - Rp109.900",
        originalPrice: "Rp81.800 - Rp240.000",
        badge: "G2G",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztd-mr1g6ztk09hg97@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/5VU37h3DUI"
    },
	{
        id: 73,
        name: "Pond's Bright Miracle Ultimate Clarity Niasorcinol Facial Foam 100gr 20x kekuatan mencerahkan & menutrisi",
        category: "Kecantikan",
        subCategory: "Pond's",        
		platform: "Shopee",
        price: "Rp33.000",
        originalPrice: "Rp44.800",
        badge: "POND'S",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134301-8260s-mkuq716en8cjcd@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/2LX0NvqfaM"
    },
	{
        id: 74,
        name: "Pond's Bright Miracle Ultimate Oil Control Facial Foam 100G 20x kekuatan mencerahkan & menutrisi",
        category: "Kecantikan",
        subCategory: "Pond's",        
		platform: "Shopee",
        price: "Rp34.400",
        originalPrice: "Rp42.000",
        badge: "POND'S",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134301-825zw-mkuq7ujwidc4b9@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1VxtOPnfCi"
    },
	{
        id: 75,
        name: "Jakarta Fashion Week 2025 - Pond's Age Miracle Hexyl Retinol: Niacinamide + Hexylresorcinol + Retinol-C. Facial Foam 100 gr",
        category: "Kecantikan",
        subCategory: "Pond's",        
		platform: "Shopee",
        price: "Rp59.600",
        originalPrice: "Rp80.000",
        badge: "POND'S",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-8262h-mln86911rmkicb.webp",
        link: "https://s.shopee.co.id/8pkU7uEKX8"
    },
	{
        id: 76,
        name: "Pond's Age Miracle Hexyl Retinol Niacinamide Day Cream 9gr (Mencerahkan Kulit dalam 7 hari dengan 10x kekuatan Anti Aging Terbaik)",
        category: "Kecantikan",
        subCategory: "Pond's",        
		platform: "Shopee",
        price: "Rp34.500",
        originalPrice: "Rp41.700",
        badge: "POND'S",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-8260w-mln868zcgweb69@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/2BDaBfXFwY"
    },
	{
        id: 77,
        name: "Pond's Bright Miracle Ultimate Acne Control Facial Foam 100G",
        category: "Kecantikan",
        subCategory: "Pond's",        
		platform: "Shopee",
        price: "Rp38.600",
        originalPrice: "Rp47.000",
        badge: "POND'S",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7r98u-lmh5ildfwx7o69@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7VF6XUhxuX"
    },
	{
        id: 78,
        name: "Pond's Bright Miracle Ultimate Oil Control Facial Foam 50G",
        category: "Kecantikan",
        subCategory: "Pond's",        
		platform: "Shopee",
        price: "Rp28.600",
        originalPrice: "Rp29.800",
        badge: "POND'S",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134301-82603-mkuq6y8k9dds14@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/8fR3vehFEX"
    },
	{
        id: 79,
        name: "Kahf Face Wash Oil and Acne Care 100 ml - Sabun Cuci Muka Pria untuk Membantu Lawan Jerawat dan Kontrol Minyak - Daily Use, Salicylic",
        category: "Kecantikan",
        subCategory: "Kahf",        
		platform: "Shopee",
        price: "Rp42.500 - Rp117.300",
        originalPrice: "Rp83.500 - Rp250.500",
        badge: "KAHF",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wi-mphdkd6ofsw188@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7fYWjtmoSa"
    },
	{
        id: 80,
        name: "Kahf Bright Revitalizing Amino Gel Face Wash 100 ml – Sabun Cuci Muka Pria Kulit Sensitif untuk Mencerahkan Wajah dengan Vitamin C",
        category: "Kecantikan",
        subCategory: "Kahf",        
		platform: "Shopee",
        price: "Rp44.500 - Rp217.580",
        originalPrice: "Rp87.500 - Rp459.500",
        badge: "KAHF",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wk-mphls0rtlrm47e@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7VF6Xc9JiM"
    },
	{
        id: 81,
        name: "Twin Pack Kahf Body Wash Relaxing and Acne Fight 200 ml - 2 pcs Sabun Mandi untuk Membantu Melawan Jerawat",
        category: "Kecantikan",
        subCategory: "Kahf",        
		platform: "Shopee",
        price: "Rp53.010",
        originalPrice: "Rp114.00",
        badge: "KAHF",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wm-mp7bwk802a6a79@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/30mhBMz6Xi"
    },
	{
        id: 82,
        name: "Kahf Oil Free Refreshing and Hydrating All-in-One PowerToning Face Spray - Advanced Zinc PCA - Semburan Muka",
        category: "Kecantikan",
        subCategory: "Kahf",        
		platform: "Shopee",
        price: "Rp83.000",
        originalPrice: "Rp158.000",
        badge: "KAHF",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7ra0h-mbf1apk0o2la42@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9Kgkj1klRw"
    },
	{
        id: 83,
        name: "Kahf Sunscreen Stick Invisible Matte (30ml) SPF 50 PA++++ Water and Sweat Resistant for Sensitive and Acne Prone Skin Type",
        category: "Kecantikan",
        subCategory: "Kahf",        
		platform: "Shopee",
        price: "Rp115.000",
        originalPrice: "Rp180.000",
        badge: "KAHF",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7ra0u-mbqfcg3w2qt8e9@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/5LAbxhSsER"
    },
	{
        id: 84,
        name: "CITRA BODY SERUM SPF 30 PA++ BIO-AHA 180ML",
        category: "Kecantikan",
        subCategory: "Citra",        
		platform: "Shopee",
        price: "Rp31.800",
        originalPrice: "Rp36.500",
        badge: "CITRA",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134301-820n3-mntuy0eak1s53b@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7fYXiGuFiX"
    },
	{
        id: 85,
        name: "CITRA BODY SERUM BRIGHT SPARKLE BIO-AHA 180ML",
        category: "Kecantikan",
        subCategory: "Citra",        
		platform: "Shopee",
        price: "Rp29.100",
        originalPrice: "Rp30.400",
        badge: "CITRA",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7ra0s-mdu3r1q8esya36@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/5VU38JEP0U"
    },
	{
        id: 86,
        name: "Citra Cream Wajah Green Tea 40 G - Moisturizer Kulit Berminyak, Anti Acne, Perawatan Jerawat",
        category: "Kecantikan",
        subCategory: "Citra",        
		platform: "Shopee",
        price: "Rp47.400",
        originalPrice: "Rp53.200",
        badge: "CITRA",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134201-7r990-looxq8nuk8re19@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7VF7W0xSLI"
    },
	{
        id: 87,
        name: "Citra UV Body Lotion Perfect Bright Bengkoang 380ML- Mencerahkan",
        category: "Kecantikan",
        subCategory: "Citra",        
		platform: "Shopee",
        price: "Rp38.600",
        originalPrice: "Rp41.700",
        badge: "CITRA",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-824i3-mpdvf7pri03k49.webp",
        link: "https://s.shopee.co.id/W5NBArbZV"
    },
	{
        id: 88,
        name: "CITRA BODY SERUM RADIANT FRESH BIO-AHA 180ML",
        category: "Kecantikan",
        subCategory: "Citra",        
		platform: "Shopee",
        price: "Rp28.500",
        originalPrice: "Rp30.300",
        badge: "CITRA",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7ra0l-mdu3r1q87s4230@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/80BO6zHN2X"
    },
	{
        id: 89,
        name: "Glow & Lovely Sunscreen Wajah UV Duo SPF 50 15g",
        category: "Kecantikan",
        subCategory: "Glow&Lovely",        
		platform: "Shopee",
        price: "Rp23.000",
        originalPrice: "Rp25.000",
        badge: "GLOW&LOVELY",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134301-7rcf2-m669iwp3ucr490@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9KglhSfFGD"
    },
	{
        id: 90,
        name: "Glow & Lovely Glassbright Gel Cleanser 75GR | Sabun Cuci Muka yang dapat Membersihkan dan Mencerahkan Wajah Secara Instan",
        category: "Kecantikan",
        subCategory: "Glow&Lovely",        
		platform: "Shopee",
        price: "Rp32.100",
        originalPrice: "Rp34.900",
        badge: "GLOW&LOVELY",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134301-823qg-morsem813dhqb0@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/5LAcw7pfYE"
    },
	{
        id: 91,
        name: "Glow & Lovely Glasshydra Gel Cleanser 75GR | Sabun Cuci Muka yang Membersihkan dan Melembabkan Kulit Tampak Bening dan Cerah",
        category: "Kecantikan",
        subCategory: "Glow&Lovely",        
		platform: "Shopee",
        price: "Rp32.100",
        originalPrice: "Rp34.900",
        badge: "GLOW&LOVELY",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134301-823ob-morsen034i6kb0@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7KvhJon5AA"
    },
	{
        id: 92,
        name: "Buy Glow & Lovely Glassbright Cream 50gr FREE Sunscreen Wajah UV Duo SPF 50 15gr",
        category: "Kecantikan",
        subCategory: "Glow&Lovely",        
		platform: "Shopee",
        price: "Rp55.900",
        originalPrice: "Rp64.000",
        badge: "GLOW&LOVELY",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134201-7ra0j-mcfssdpy5dmt7c@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/8pkV6almQi"
    },
	{
        id: 93,
        name: "Glow & Lovely DermaGlow Multivitamin Cream 46g (Wajah +40% Lebih Cerah Glowing)",
        category: "Kecantikan",
        subCategory: "Glow&Lovely",        
		platform: "Shopee",
        price: "Rp41.400",
        originalPrice: "Rp48.300",
        badge: "GLOW&LOVELY",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134301-82580-mqpxue309gjybd@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/6Ajjvi2P1k"
    },
	{
        id: 94,
        name: "Vaseline Soft Glow Gluta Vitamin Body Serum SPF20 dengan Niacinamide - Body Serum untuk Perlindungan UV, Kulit Cerah & Lembap",
        category: "Kecantikan",
        subCategory: "Vaseline",        
		platform: "Shopee",
        price: "Rp22.400",
        originalPrice: "Rp22.600",
        badge: "VASELINE",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7r98o-lkyqo8zlnpgr0f@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/4VbVwfYfmz"
    },
	{
        id: 95,
        name: "Vaseline Multi Purpose Repairing Jelly Aloe 50 ml",
        category: "Kecantikan",
        subCategory: "Vaseline",        
		platform: "Shopee",
        price: "Rp30.700",
        originalPrice: "Rp34.000",
        badge: "VASELINE",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/13666e35b31bb8e4edaadb4dede5475e@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/70IqvHmkBk"
    },
	{
        id: 96,
        name: "VASELINE SOFT GLOW GLUTA VITAMIN SPF 20 BODY SERUM NIACINAMIDE 180ML",
        category: "Kecantikan",
        subCategory: "Vaseline",        
		platform: "Shopee",
        price: "Rp34.700",
        originalPrice: "Rp37.300",
        badge: "VASELINE",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134201-7r98q-lt27l5b2ph5841@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/111dmHtaK3"
    },
	{
        id: 97,
        name: "[JENNIE'S PICK] Vaseline Gluta-Hya Overnight Radiance Repair Serum Burst Lotion dengan 70X Melatonic-Peptide Complex",
        category: "Kecantikan",
        subCategory: "Vaseline",        
		platform: "Shopee",
        price: "Rp58.500",
        originalPrice: "Rp65.200",
        badge: "VASELINE",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134301-823ob-mp8tqzarrzm71a@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1LeUAuk4hy"
    },
	{
        id: 98,
        name: "VASELINE HIJAB RADIANT GLUTA VITAMIN COOLING SERUM WITH 12HOUR 180ML - body serum",
        category: "Kecantikan",
        subCategory: "Vaseline",        
		platform: "Shopee",
        price: "Rp33.600",
        originalPrice: "Rp37.200",
        badge: "VASELINE",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134201-7r98s-looxrb4o9px75b@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/50XmXgHlWj"
    },
	{
        id: 99,
        name: "[JENNIE'S PICK] Vaseline Healthy Bright? Gluta Hyaluron Niacinamide Serum Lotion Dewy Radiance 330Ml",
        category: "Kecantikan",
        subCategory: "Vaseline",        
		platform: "Shopee",
        price: "Rp75.100",
        originalPrice: "Rp90.700",
        badge: "VASELINE",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134301-8259c-mqx7yw4dm6mc6d@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/5ArCk18UCN"
    },
	{
        id: 100,
        name: "Barber Daily Acne Care & Oil Control Face Wash 100mL",
        category: "Kecantikan",
        subCategory: "Makarizo",        
		platform: "Shopee",
        price: "Rp37.800",
        originalPrice: "Rp45.500",
        badge: "MAKARIZO",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224q-mkvxfe1se9l0e1@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/3LPYYm2CH6"
    },
	{
        id: 101,
        name: "Acne Care & Oil Control Moisturizer 30mL",
        category: "Kecantikan",
        subCategory: "Makarizo",        
		platform: "Shopee",
        price: "Rp37.800",
        originalPrice: "Rp65.000",
        badge: "MAKARIZO",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-822x4-mi3zcv3qrsoy61@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/8V7eiIrkzA"
    },
	{
        id: 102,
        name: "128 Saccharina Japonica Bright & Radiance Moisturizer Tube 50mL by Makarizo",
        category: "Kecantikan",
        subCategory: "Makarizo",        
		platform: "Shopee",
        price: "Rp63.100",
        originalPrice: "Rp262.250",
        badge: "MAKARIZO",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224r-mjnucixsifpf7e@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/5q6tXTXyir"
    },
	{
        id: 103,
        name: "128 Makarizo Pro Acne Defense Facial Wash - Sabun Cuci Muka Untuk Jerawat",
        category: "Kecantikan",
        subCategory: "Makarizo",        
		platform: "Shopee",
        price: "Rp36.400",
        originalPrice: "Rp87.250",
        badge: "MAKARIZO",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-8262v-mmgwif3ce8057a@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/111dmbdKDs"
    },
	{
        id: 104,
        name: "128 Saccharina Japonica Bright & Radiance Facial Wash Tube 100mL by Makarizo",
        category: "Kecantikan",
        subCategory: "Makarizo",        
		platform: "Shopee",
        price: "Rp36.400",
        originalPrice: "Rp87.250",
        badge: "MAKARIZO",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztn-mq7dosqlzpc166@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/80BO7UyOXY"
    },
	{
        id: 105,
        name: "[BUNDLE BRIGHT] 128 Makarizo Paket Kulit Cerah Glowing - Bright & Radiance Facial Wash, Toner, Serum, Moisturizer - Efektif Mencerahkan",
        category: "Kecantikan",
        subCategory: "Makarizo",        
		platform: "Shopee",
        price: "Rp187.000",
        originalPrice: "Rp858.000",
        badge: "MAKARIZO",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wg-moothh0d4xlbc6@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1gHKZsawys"
    },
	{
        id: 305,
        name: "Hanasui Serum Vitamin C - Mencerahkan & Pudarkan Bintik Hitam 2% Vitamin C 2% Niacinamide 1% Betaine",
        category: "Kecantikan",
        subCategory: "Hanasui",        
		platform: "Shopee",
        price: "Rp33.178 - Rp87.469",
        originalPrice: "Rp39.032 - Rp117.095",
        badge: "HANASUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7ra0u-mdpip1tggxovfd@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/4AynvwN3vi"
    },
	{
        id: 405,
        name: "Hanasui Power Post Acne Serum - Pudarkan Bekas Jerawat PIE & PIH Mencerahkan dan Kurangi Kemerahan Cegah Jerawat Kembali",
        category: "Kecantikan",
        subCategory: "Hanasui",        
		platform: "Shopee",
        price: "Rp36.430 - Rp96.432",
        originalPrice: "Rp42.858 - Rp128.575",
        badge: "HANASUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7ra0n-mdpip1tgbbf343@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/8KoMtko6bF"
    },
	{
        id: 505,
        name: "Hanasui Power Acne Serum - Jerawat & Beruntusan Menenangkan & Kurangi Produksi Minyak Salicylic Acid dan Glycolic Acid",
        category: "Kecantikan",
        subCategory: "Hanasui",        
		platform: "Shopee",
        price: "Rp36.430 - Rp96.432",
        originalPrice: "Rp42.858 - Rp128.575",
        badge: "HANASUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7ra0r-mdmx69u1tos468@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/AAG159KryK"
    },
	{
        id: 605,
        name: "Hanasui Clay Stick Mask - Masker Wajah Mencerahkan Mengangkat Komedo Menyamarkan Pori & Menenangkan Jerawat",
        category: "Kecantikan",
        subCategory: "Hanasui",        
		platform: "Shopee",
        price: "Rp44.625 - Rp112.493",
        originalPrice: "Rp52.500 - Rp133.920",
        badge: "HANASUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zto-mf7p18wt4z6393@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/AAG15Aq9pS"
    },
	{
        id: 705,
        name: "Hanasui Glow Expert Gentle Cleanser New Improved Formula - Sabun Cuci Muka Foam Cerah & Kurangi Kusam Lembut Tidak Ketarik",
        category: "Kecantikan",
        subCategory: "Hanasui",        
		platform: "Shopee",
        price: "Rp34.871",
        originalPrice: "Rp41.024",
        badge: "HANASUI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7rasd-m31gflqrabcdd1@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7VFFuMo3TO"
    },
	{
        id: 106,
        name: "Wear Kaza Indonesia - Ather Stripe Boxy Shirt",
        category: "For Him",
        subCategory: "Shirt Him",        
		platform: "Shopee",
        price: "Rp147.000",
        originalPrice: "Rp187.000",
        badge: "WEAR KAZA",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7rasd-m2f14q7jfdl638@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/5LAkbtS7Um"
    },
	{
        id: 107,
        name: "Kemeja Pria Lengan Panjang Kotak Kotak Oversize Kekinian Baju Cowok Casual Fashion Pria Premium",
        category: "For Him",
        subCategory: "Shirt Him",        
		platform: "Shopee",
        price: "Rp155.900",
        originalPrice: "",
        badge: "KUTAS",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wm-mmftuwwfhngv2e@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7ps2HIj9Pa"
    },
	{
        id: 108,
        name: "Kemeja Corduroy Pria Lengan Panjang Polos | Gaya Korea Kasual Model Modern Premium Stylish",
        category: "For Him",
        subCategory: "Shirt Him",        
		platform: "Shopee",
        price: "Rp154.980",
        originalPrice: "",
        badge: "KUTAS",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wq-mlg76s65ks1s9c@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9V0JZw7NK4"
    },
	{
        id: 109,
        name: "HIGHTY Khaki Grid Cotton Shirt | Kemeja Lengan Panjang Pria",
        category: "For Him",
        subCategory: "Shirt Him",        
		platform: "Shopee",
        price: "Rp190.000",
        originalPrice: "Rp275.000",
        badge: "BROODIS",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7rasd-m4fn8lii6u4se6@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9pd9ybv4Xj"
    },
	{
        id: 110,
        name: "NAWLA - Baju Atasan Kemeja Pria Lengan Panjang Formal Fit Motif Pinstripe Salur Garis",
        category: "For Him",
        subCategory: "Shirt Him",        
		platform: "Shopee",
        price: "Rp165.820",
        originalPrice: "",
        badge: "NAWLA",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224t-mi1iw7m235e054@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9ANSnT7Aes"
    },
	{
        id: 111,
        name: "Troy Company Tshirt Black Tribal Etnic - Kaos Pria Hitam Lengan Pendek MTD 286",
        category: "For Him",
        subCategory: "T-Shirt",        
		platform: "Shopee",
        price: "Rp95.900",
        originalPrice: "",
        badge: "TROY COMPANY",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7ra0p-mcsqkslwqa6wa3@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/6L3HpozZbP"
    },
	{
        id: 112,
        name: "GOOD BYE EX - Tshirt Cotton 24s Classy List Black",
        category: "For Him",
        subCategory: "T-Shirt",        
		platform: "Shopee",
        price: "Rp99.900",
        originalPrice: "Rp239.000",
        badge: "GOOD BYE",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-82251-mjqohfr1ciyp44@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/2qTPefYEmP"
    },
	{
        id: 113,
        name: "ETHEREAL - Tshirt Oversized Pria Wanita Distro Polaris",
        category: "For Him",
        subCategory: "T-Shirt",        
		platform: "Shopee",
        price: "Rp99.000",
        originalPrice: "Rp200.000",
        badge: "ETHRL",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7r98x-lvl3nwtr9epc5a@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/70IycZpm9x"
    },
	{
        id: 114,
        name: "HLPD Weirdworld Kaos Tshirt Boxy Oversize Pecah Pola - Chiv Polos Beige",
        category: "For Him",
        subCategory: "T-Shirt",        
		platform: "Shopee",
        price: "Rp99.900",
        originalPrice: "Rp199.000",
        badge: "HLPD",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-825aw-mg0ku5bmd43u62@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/BSbApcQ3H"
    },
	{
        id: 115,
        name: "[Carture] Tshirt Cotton Combed 24s CT09 PXZHLCKD Premium 100%",
        category: "For Him",
        subCategory: "T-Shirt",        
		platform: "Shopee",
        price: "Rp65.569",
        originalPrice: "Rp100.000",
        badge: "CARTURE",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224z-mhn39nh49p8k0a@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/20uIfBZzXO"
    },
	{
        id: 116,
        name: "CLU3Men Kaos Polo Knit Tweed Pria – Bahan Tekstur Premium, Polos, Lengan Pendek CM2",
        category: "For Him",
        subCategory: "Polo Shirt",        
		platform: "Shopee",
        price: "Rp85.000 - Rp88.374",
        originalPrice: "Rp250.000",
        badge: "CLU3MEN",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wk-mnn0k0ti77k5c2@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/4AyjxVTBTI"
    },
	{
        id: 198,
        name: "OOTDSUPPLY Oversize Polo T-shirt Essentials Black & Milo | Kaos Polo Pria dan Wanita OVZ-PS020",
        subCategory: "Polo Shirt",        
		platform: "Shopee",
        price: "Rp115.000 - Rp125.000",
        originalPrice: "Rp225.000",
        badge: "OOTDSUPPLY",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7r98q-lowc8cd9h85vd0@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/2BDisx34Ak"
    },
	{
        id: 199,
        name: "Troy Company Wangky Polo Shirt Full Black Amoeba - Kaos Polo Hitam WKD 2988",
        category: "For Him",
        subCategory: "Polo Shirt",        
		platform: "Shopee",
        price: "Rp127.900",
        originalPrice: "",
        badge: "TROY",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7rasb-m5y2qgvr9dd459@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1qasUOywFN"
    },
	{
        id: 201,
        name: "Matt Sarwey Heavyweight Kaos Polo Oversized Kaos Kerah 16s Digression Hitam",
        category: "For Him",
        subCategory: "Polo Shirt",        
		platform: "Shopee",
        price: "Rp136.500",
        originalPrice: "",
        badge: "MATT SARWEY",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7rbk8-m6nnv21uj5bb50.webp",
        link: "https://s.shopee.co.id/qiLIafBOD"
    },
	{
        id: 202,
        name: "Tuan Kong kaos kerah pria lengan pendek sablon Polo Shirt Pria polo shirt pria premium",
        category: "For Him",
        subCategory: "Polo Shirt",        
		platform: "Shopee",
        price: "Rp126.300",
        originalPrice: "",
        badge: "TUAN KONG",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztl-mephadlg08owfb@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9zwaDX8GIr"
    },
	{
        id: 117,
        name: "House of Smith Sweater Pria - Wade Halfzip Oversized - Halfzip Oversize",
        category: "For Him",
        subCategory: "Sweater & Hoodie",        
		platform: "Shopee",
        price: "Rp195.000",
        originalPrice: "",
        badge: "HOUSE OF SMITH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wh-moj6f4juthj6bb.webp",
        link: "https://s.shopee.co.id/BSbuni9nG"
    },
	{
        id: 118,
        name: "Dobujack Sweater Noxa Black Crewneck",
        category: "For Him",
        subCategory: "Sweater & Hoodie",        
		platform: "Shopee",
        price: "Rp195.000",
        originalPrice: "",
        badge: "DOBUJACK",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7ra0r-mbdd3s15t3tl65@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/8KoJeFopfg"
    },
	{
        id: 119,
        name: "Benidson Sweater Crewneck Black freshman",
        category: "For Him",
        subCategory: "Sweater & Hoodie",        
		platform: "Shopee",
        price: "Rp170.000",
        originalPrice: "",
        badge: "BENIDSON",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-23020-88qg0cwdmbnvdf@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9ANQdpkF3m"
    },
	{
        id: 120,
        name: "Bloods Series Sweater Crewneck Wanderer 01",
        category: "For Him",
        subCategory: "Sweater & Hoodie",        
		platform: "Shopee",
        price: "Rp197.500 - Rp395.000",
        originalPrice: "Rp395.000",
        badge: "BLOODS",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224v-ml1m1vvrb8qp9e@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/19Bj47lm1"
    },
	{
        id: 121,
        name: "OVRDZ - Sweater Crewneck Linea Unisex",
        category: "For Him",
        subCategory: "Sweater & Hoodie",        
		platform: "Shopee",
        price: "Rp114.000",
        originalPrice: "",
        badge: "OVRDZ",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224q-mfuq4czcefwtc9.webp",
        link: "https://s.shopee.co.id/7AcMGKfzKm"
    },
	{
        id: 122,
        name: "Dobujack Fujin Black Hoodie",
        category: "For Him",
        subCategory: "Sweater & Hoodie",        
		platform: "Shopee",
        price: "Rp258.000",
        originalPrice: "",
        badge: "DOBUJACK",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zth-mf98sk03yxajdd@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/3Vj3vcPbXP"
    },
	{
        id: 123,
        name: "Troy Company Boxy Hoodie Starlight Black Neo Motion - Hoodie Boxy Reflective Hitam BSH 3376",
        category: "For Him",
        subCategory: "Sweater & Hoodie",        
		platform: "Shopee",
        price: "Rp234.900",
        originalPrice: "",
        badge: "TROY",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-82250-mgbn5j7znz0t70@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9KgqsRI9y1"
    },
	{
        id: 124,
        name: "House of Smith Sweater Hoodie Oversize Pria - S World Hoodie Black #4",
        category: "For Him",
        subCategory: "Sweater & Hoodie",        
		platform: "Shopee",
        price: "Rp175.000",
        originalPrice: "",
        badge: "HOUSE OF SMITH",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wg-moj66baquz9ecf@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/2g9wwIgZGY"
    },
	{
        id: 125,
        name: "Dobujack Hegas Black Hoodie",
        category: "For Him",
        subCategory: "Sweater & Hoodie",        
		platform: "Shopee",
        price: "Rp258.000",
        originalPrice: "",
        badge: "DOBUJACK",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-822wl-mphtk4ng5jwia7@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/AUsoGiO6Bi"
    },
	{
        id: 126,
        name: "Breakside Hoodie Epic Sunday - Black Sweater Pria",
        category: "For Him",
        subCategory: "Sweater & Hoodie",        
		platform: "Shopee",
        price: "Rp304.900",
        originalPrice: "",
        badge: "BREAKSIDE",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7ra0s-mcrcc1g0t44899@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7VFChGxkfJ"
    },
	{
        id: 127,
        name: "Odelia - Carmia Daily Shirt | Kemeja Basic I Atasan Wanita",
        category: "For Her",
        subCategory: "Shirt Her",        
		platform: "Shopee",
        price: "Rp219.870 - Rp349.000",
        originalPrice: "Rp349.000",
        badge: "ODELIA",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7ra0i-mbbyf0tb858866@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/9V0H6DYFaB"
    },
	{
        id: 128,
        name: "Ghalibia.id - Adele Shirt | Atasan Wanita | Kemeja Wanita | Jumbo Big Size",
        category: "For Her",
        subCategory: "Shirt Her",        
		platform: "Shopee",
        price: "Rp114.912 - Rp131.040",
        originalPrice: "Rp159.600 - Rp182.000",
        badge: "GHALIBIA",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224q-miuzoemnlv5x3e@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/3B6DZCqA7u"
    },
	{
        id: 129,
        name: "MDLY Lacey Shirt Atasan Wanita Kemeja Kerja Bahan Premium Terbaru Motif polos Shirt Casual",
        category: "For Her",
        subCategory: "Shirt Her",        
		platform: "Shopee",
        price: "Rp210.000",
        originalPrice: "",
        badge: "MDLY",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224p-mg3aimqyifbd68@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/6VMfXNnsan"
    },
	{
        id: 130,
        name: "Mayoutfit Zyrra Shirt | Kemeja Basic Poplin Wanita Aksen Stripe Bisban",
        category: "For Her",
        subCategory: "Shirt Her",        
		platform: "Shopee",
        price: "Rp177.500",
        originalPrice: "Rp338.000",
        badge: "MAYOUTFIT",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztj-mejjdtw95clea2@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/8V7jvIIoT8"
    },
	{
        id: 131,
        name: "ZIANISA - Blouse Wanita Brokat Cassia Series | Atasan Wanita Full Kancing | Blouse Kerah Bulat",
        category: "For Her",
        subCategory: "Shirt Her",        
		platform: "Shopee",
        price: "Rp139.000",
        originalPrice: "Rp349.000",
        badge: "ZIANISA",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7rase-m0jktkobqzwn3d@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/5q6ykvSlW0"
    },
	{
        id: 132,
        name: "HaymeeIDN - Ariana Tunik Stripe | Atasan Tunik Salur Bahan Linen",
        category: "For Her",
        subCategory: "Tunic",        
		platform: "Shopee",
        price: "Rp104.280",
        originalPrice: "",
        badge: "HAYMEEIDN",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7rasi-m182hjwpk5s208@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1qapzlEBsg"
    },
	{
        id: 133,
        name: "MFMW Slubby Tunik Military Olive Motif Kotak",
        category: "For Her",
        subCategory: "Tunic",        
		platform: "Shopee",
        price: "Rp233.000",
        originalPrice: "",
        badge: "MFMW",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-7ra1f-m55jixn53n1453@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/19BoT0eps"
    },
	{
        id: 134,
        name: "MFMW Zanelva Atasan Blouse Cream Motif Kotak",
        category: "For Her",
        subCategory: "Tunic",        
		platform: "Shopee",
        price: "Rp207.000",
        originalPrice: "",
        badge: "MFMW",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-8260s-mjkqwimm8e82d4@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/4LIAyqDw1C"
    },
	{
        id: 135,
        name: "MFMW Berdine Tunik Brown Motif Salur",
        category: "For Her",
        subCategory: "Tunic",        
		platform: "Shopee",
        price: "Rp197.000",
        originalPrice: "",
        badge: "MFMW",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-7rcdy-lrig6k218x1bf4@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/4AykmlLHwe"
    },
	{
        id: 136,
        name: "COTTON INSTYLE – Zafrana Sarimbit Tunik Wanita Bahan Cotton Dobby",
        category: "For Her",
        subCategory: "Tunic",        
		platform: "Shopee",
        price: "Rp187.900",
        originalPrice: "",
        badge: "COTTON INSTYLE",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztk-mqpn5utyrz0i19@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/30mnSKgg2i"
    },
	{
        id: 137,
        name: "Nibras Hijab x Kalasiris Atasan Tunik Blouse Wanita Lengan Panjang Katun Bordir - Noura Tunic",
        category: "For Her",
        subCategory: "Tunic",        
		platform: "Shopee",
        price: "Rp213.750",
        originalPrice: "",
        badge: "KALASIRS",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7rbk3-m8vdtuz6oufl62@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/6fg5p6sRkf"
    },
	{
        id: 138,
        name: "TAFANA - Jenni Dress Muslim Korea Bahan Crinkle gamis motif bunga dress floral korea vintage",
        category: "For Her",
        subCategory: "Dress",        
		platform: "Shopee",
        price: "Rp154.000",
        originalPrice: "Rp195.000",
        badge: "TAFANA",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7r98q-luzu0i4z8uqla9@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/AKZOCXEjON"
    },
	{
        id: 139,
        name: "Mulan Dress Edisi Yasmin Varian Mocca | S M L XL | Busana Wanita | Fashion Muslim | Pakaian Wanita | Gamis | Korea Style | Baju Pesta",
        category: "For Her",
        subCategory: "Dress",        
		platform: "Shopee",
        price: "Rp213.000",
        originalPrice: "",
        badge: "AMIE",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7qukx-lh39qx6vieuofd@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1gHPsdzYkw"
    },
	{
        id: 140,
        name: "Shirin Zein - Dress Gamis Terbaru Mewah Elegan 2026 Bahan Dior Slik Premium Thalia Series Dpk 3",
        category: "For Her",
        subCategory: "Dress",        
		platform: "Shopee",
        price: "Rp173.666 - Rp197.400",
        originalPrice: "Rp208.000 - Rp210.000",
        badge: "SHIRIN",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224p-mk98v4m0grno48@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/6VMfdtRgIy"
    },
	{
        id: 141,
        name: "Silmi | Loly - Dress Muslim Korean Style Wanita Hijab",
        category: "For Her",
        subCategory: "Dress",        
		platform: "Shopee",
        price: "Rp242.820 - Rp255.600",
        originalPrice: "Rp342.000 - Rp360.000",
        badge: "SILMI",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-8224t-mgbqn68hgxs976@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/AAG0FcDq9C"
    },
	{
        id: 142,
        name: "Zivana Dress Gamis Daily Bahan Dobby Pop Warna Coksu Korean Style Baju OOTD Polos Casual Outfit 2025",
        category: "For Her",
        subCategory: "Dress",        
		platform: "Shopee",
        price: "Rp84.942",
        originalPrice: "Rp320.560",
        badge: "AMIE",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-7ras9-m4k8dk51ro8k7f@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/5ArKIc9oG2"
    },
	{
        id: 143,
        name: "Neo Coffee Kopi Instan Moccachino Pack 20 gr isi 6 + 3 pcs x3",
        category: "Minuman",
        subCategory: "Kopi",        
		platform: "Shopee",
        price: "Rp29.100",
        originalPrice: "Rp34.100",
        badge: "WINGS",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134201-82250-mgrcy5gcd6vd08@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/8V7mHChUH6"
    },
	{
        id: 144,
        name: "Kopi Luwak White Koffie Tarik Malaka 10x25gr (Renceng)",
        category: "Minuman",
        subCategory: "Kopi",        
		platform: "Shopee",
        price: "Rp18.500",
        originalPrice: "Rp28.000",
        badge: "KOPI LUWAK",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81zto-mezhi403herwab@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/5VUAhj24Lg"
    },
	{
        id: 145,
        name: "Kopi Luwak White Koffie Ovalcino Renceng 15x25gr",
        category: "Minuman",
        subCategory: "Kopi",        
		platform: "Shopee",
        price: "Rp15.380",
        originalPrice: "Rp24.000",
        badge: "KOPI LUWAK",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/675c0ac76aea826418c383963288cca9@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/4LIDJbEuA2"
    },
	{
        id: 146,
        name: "Top Coffee Kopi Instan Avocado 22 gr isi 6 + 3 pcs",
        category: "Minuman",
        subCategory: "Kopi",        
		platform: "Shopee",
        price: "Rp12.700",
        originalPrice: "Rp15.200",
        badge: "WINGS",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134201-7r990-lsw8ylzlc1gm0c@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/7KvotCe1yI"
    },
	{
        id: 147,
        name: "Top Coffee Kopi Barista Special Blend Pack 25 gr isi 6 + 3 pcs x3",
        category: "Minuman",
        subCategory: "Kopi",        
		platform: "Shopee",
        price: "Rp33.400",
        originalPrice: "Rp39.500",
        badge: "WINGS",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/sg-11134201-7rblx-lo0wio2drglk09@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/8AUvslDIOD"
    },
	{
        id: 148,
        name: "Kopi Luwak Super Hemat Black Coffee Bag 100gr + 100gr",
        category: "Minuman",
        subCategory: "Kopi",        
		platform: "Shopee",
        price: "Rp16.420",
        originalPrice: "Rp25.000",
        badge: "KOPI LUWAK",
        shopBadge: "Shopee Mall",
        image: "https://down-id.img.susercontent.com/file/id-11134207-81ztl-mefmhas84h6v00@resize_w900_nl.webp",
        link: "https://s.shopee.co.id/1LebkF0Htr"
    },

    // --- PRODUK LYNK.ID & DIGITAL ---
    {
        id:150 ,
        name: "Worksheet Matematika Dasar Anak Anak: Tracing Angka 1-10 & Game Mencocokkan Gambar",
        category: "Produk Digital",
        subCategory: "Worksheet",
        platform: "Lynk.id",
        price: "IDR 9,000",
        originalPrice: "IDR 15,000",
        badge: "WORKSHEET",
        image: "https://cdn.lynkid.my.id/products/29-06-2026/1782724804435_8522261.webp",
        link: "https://lynk.id/yakinbeli/e2yvkjyr1o52"
    },
    {
        id: 151 ,
        name: "Worksheet Berhitung Anak TK - PAUD: Media Belajar Logika & Angka Populer",
        category: "Produk Digital",
        subCategory: "Worksheet",
        platform: "Lynk.id",
        price: "IDR 9,000",
        originalPrice: "IDR 15,000",
        badge: "WORKSHEET",
        image: "https://cdn.lynkid.my.id/products/29-06-2026/1782726271895_6537390.webp",
        link: "https://lynk.id/yakinbeli/114z5p6wgzoj"
    },
    {
        id: 152 ,
        name: "Premium Construction Busy Book PDF - Media Belajar Interaktif Anak (PAUD/TK)",
        category: "Produk Digital",
        subCategory: "Worksheet",
        platform: "Lynk.id",
        price: "IDR 9,000",
        originalPrice: "IDR 15,000",
        badge: "WORKSHEET",
        image: "https://cdn.lynkid.my.id/products/01-07-2026/1782881806147_5047862.webp",
        link: "https://lynk.id/yakinbeli/0y621mqm6661"
    },
    {
        id: 153 ,
        name: "Worksheet Fun Connect the Dots Activity Book (PDF) – Buku Latihan Menghubungkan Titik Angka.",
        category: "Produk Digital",
        subCategory: "Worksheet",
        platform: "Lynk.id",
        price: "IDR 9,000",
        originalPrice: "IDR 15,000",
        badge: "WORKSHEET",
        image: "https://cdn.lynkid.my.id/products/05-07-2026/1783233687078_1460528.webp",
        link: "https://lynk.id/yakinbeli/oo6zvyo1e2nn"
    },
	{
        id: 154 ,
        name: "Worksheet Anak: Petualangan Labirin Huruf & Bentuk (Superhero Theme).",
        category: "Produk Digital",
        subCategory: "Worksheet",
        platform: "Lynk.id",
        price: "IDR 9,000",
        originalPrice: "IDR 15,000",
        badge: "WORKSHEET",
        image: "https://cdn.lynkid.my.id/products/06-07-2026/1783329729656_8860378.webp",
        link: "https://lynk.id/yakinbeli/zwd6w5897210"
    },
	{
        id: 155 ,
        name: "E-Book Printable Worksheet Anak: Lembar Kerja Mencocokkan Bayangan (Shadow Game) – Format PDF.",
        category: "Produk Digital",
        subCategory: "E-Book",
        platform: "Lynk.id",
        price: "IDR 8,000",
        originalPrice: "IDR 14,000",
        badge: "E-BOOK",
        image: "https://cdn.lynkid.my.id/products/05-07-2026/1783229791453_2557332.webp",
        link: "https://lynk.id/yakinbeli/qkjwgo5q71xj"
    },
	{
        id: 156 ,
        name: "E-Book Printable Worksheet Anak: Lembar Kerja Menghubungkan Gambar (Matching Game).",
        category: "Produk Digital",
        subCategory: "E-Book",
        platform: "Lynk.id",
        price: "IDR 9,000",
        originalPrice: "IDR 15,000",
        badge: "E-BOOK",
        image: "https://cdn.lynkid.my.id/products/05-07-2026/1783229277900_3458454.webp",
        link: "https://lynk.id/yakinbeli/95qdze3e3041"
    },
	{
        id: 157 ,
        name: "E-Book Math Belajar Menulis Angka, Berhitung & Mewarnai",
        category: "Produk Digital",
        subCategory: "E-Book",
        platform: "Lynk.id",
        price: "IDR 9,000",
        originalPrice: "IDR 15,000",
        badge: "E-BOOK",
        image: "https://cdn.lynkid.my.id/products/05-07-2026/1783228454969_2424015.webp",
        link: "https://lynk.id/yakinbeli/48k2qyz4pn0k"
    },
	{
        id: 158 ,
        name: "E-Book Interactive Printable Maze Game: Lembar Kerja Labirin Hewan & Sekolah Anak.",
        category: "Produk Digital",
        subCategory: "E-Book",
        platform: "Lynk.id",
        price: "IDR 9,000",
        originalPrice: "IDR 15,000",
        badge: "E-BOOK",
        image: "https://cdn.lynkid.my.id/products/05-07-2026/1783223220173_3728252.webp",
        link: "https://lynk.id/yakinbeli/m9d8egp1q8w2"
    },
	{
        id: 159 ,
        name: "E-Book Media Edukasi Interaktif untuk Menguasai Bentuk Geometri Dasar Sejak Dini!",
        category: "Produk Digital",
        subCategory: "E-Book",
        platform: "Lynk.id",
        price: "IDR 9,000",
        originalPrice: "IDR 15,000",
        badge: "E-BOOK",
        image: "https://cdn.lynkid.my.id/products/03-07-2026/1783060660876_2536172.webp",
        link: "https://lynk.id/yakinbeli/9716emykvokm"
    }
];